# Yaml files can end in .yml or .yaml

name: GitActions Demo
on: [push]

# What jobs are part of this workflow
jobs:
  action_demo:
    # runs-on is what type of OS is our pipeline running on
    runs-on: ubuntu-latest
    # For this job, what do you want it to do?
    steps:
    - run: echo 'Hello world!'
    - run: pwd
    - run: ls
    - run: echo 'Job status is ${{job.status}}'
