# Yaml files can end in .yml or .yaml 

name: GitActions Demo
on: [push] # In what event does this workflow run

# Global Variables go BEFORE jobs:
env: 
  GLOBAL_VAR: "This is public!"

# What jobs are part of this workflow
jobs: 
  action_demo:
    # runs-on is what type of OS is our pipeline running on
    runs-on: ubuntu-latest
    # For this job, what do you want it to do?
    steps:
    - run: echo 'Hello World!'
    - run: pwd 
    - run: ls
    - run: echo 'Job status is ${{job.status}}'

  # This job will be focused on cloning our repo
  clone_demo:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out Repo
      uses: actions/checkout@v3
    - name: List contents of current directory
      run: ls -al
    - name: Run a python script
      run: python script.py

  # environment variable access or secret access keys 
  # Storing private data as variables means they're not public
  # erwkugfre8gergerg0er8gger8 - access key / key 

  variable_job: 
    env: 
      SECRET_TEXT: ${{secrets.SUPER_SECRET_TEXT}}
    runs-on: ubuntu-latest
    steps:
    - name: Print global variable
      run: echo $GLOBAL_VAR
    - name: print Local variable
      run: echo $LOCAL_VAR
    - name: Print secret variable
      run: echo $SECRET_TEXT
